[build]
builder = "NIXPACKS"

[phases.build]
cmds = [
  "cd /app && npm install",
  "cd /app && npm run build --filter=@matchpulse/api"
]

[phases.start]
cmds = ["cd /app/apps/api && npm run start"]

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
